var AopenPhotoSwipe = function() {
    var pswpElement = document.querySelectorAll('.pswp')[0];

    // build items array
    var items = [
        {
            src: '/static/img/android-development/1.png',
            w: 540,
            h: 960,
            title: 'App using Google Graph API to display equation in customizable viewing window'
        },
         {
            src: '/static/img/android-development/2.png',
            w: 540,
            h: 960,
            title: 'A chemistry simulation modeling the interactions between nonmetals; the app is targeted towards aspiring chemists needing to practice their covalent bonding diagrams '
        },
        {
            src: '/static/img/android-development/3.png',
            w: 540,
            h: 960,
            title: 'Up to degree 3 polynomials, the program processes degree coefficients into equation zeros; algorithm supports imaginary inputs'
        },
        {
            src: '/static/img/android-development/4.png',
            w: 540,
            h: 960,
            title: 'Using online medical data and artifical intelligence, application makes predictive medical diagnosis based on checked symptoms'
        },
        {
            src: '/static/img/android-development/5.png',
            w: 540,
            h: 960,
            title: 'Generates secure password as predicated upon scientifically analyzed criteria and keywords entered by user'
        }
    ];
    
    // define options (if needed)
    var options = {
			 // history & focus options are disabled on CodePen        
      	history: false,
      	focus: false,

        showAnimationDuration: 0,
        hideAnimationDuration: 0
        
    };
    
    var gallery = new PhotoSwipe( pswpElement, PhotoSwipeUI_Default, items, options);
    gallery.init();
};


var BopenPhotoSwipe = function() {
    var pswpElement = document.querySelectorAll('.pswp')[0];

    // build items array
    var items = [
        {
            src: '/static/img/spiggot-development/1.png',
            w: 633,
            h: 588,
            title: 'Console log generated by host'
        },
        {
            src: '/static/img/spiggot-development/2.png',
            w: 1366,
            h: 728,
            title: 'Screenshot of code editor involved in Java programming for Spiggot plugin development'
        },
        {
            src: '/static/img/spiggot-development/3.png',
            w: 1280,
            h: 800,
            title: 'Example of published project on Spiggot interface'
        }
    ];
    
    // define options (if needed)
    var options = {
			 // history & focus options are disabled on CodePen        
      	history: false,
      	focus: false,

        showAnimationDuration: 0,
        hideAnimationDuration: 0
        
    };
    
    var gallery = new PhotoSwipe( pswpElement, PhotoSwipeUI_Default, items, options);
    gallery.init();
};
var CopenPhotoSwipe = function() {
    var pswpElement = document.querySelectorAll('.pswp')[0];

    // build items array
    var items = [
        {
            src: '/static/img/video-production/1.png',
            w: 1170,
            h: 546,
            title: 'Channel #1 - Active from 2016 to Present'
        },
        {
            src: '/static/img/video-production/2.png',
            w: 1168,
            h: 547,
            title: 'Channel #2 - Active from 2012 to 2016'
        },
        {
            src: '/static/img/video-production/3.png',
            w: 1166,
            h: 556,
            title: 'Channel #3 - Active from 2011 to 2013'
        }        
    ];
    
    // define options (if needed)
    var options = {
			 // history & focus options are disabled on CodePen        
      	history: false,
      	focus: false,

        showAnimationDuration: 0,
        hideAnimationDuration: 0
        
    };
    
    var gallery = new PhotoSwipe( pswpElement, PhotoSwipeUI_Default, items, options);
    gallery.init();
};

document.getElementById('open1').onclick = AopenPhotoSwipe;
document.getElementById('open2').onclick = BopenPhotoSwipe;
document.getElementById('open3').onclick = CopenPhotoSwipe;



